### ISSUE TITLE
APP Andorid4.4閃退

### ISSUE THREAD

**Issue by yiming330** [yiming330/pqi-air-bank#1]
Please provide more details for developer to look into the issue.
1. 使用者用哪一個device (看標題應該是裝Android 4.4版本的作業系統)
2. 使用者閃退的操作步驟
3. 如果可以, 是否能借到同型號的手機

**Comment by PQI-APP** [comment]
1. Android 4.4
2. 依據消費者告知 是直接開啟後就退出了
3. 無法 消費者在香港 使用Google Nexus 5.

**Comment by wuboy0307** [comment]
1. 使用 hTC M8 4.4.2 測試 沒有閃退的狀況
2. 使用 模擬器 Google Nexus 7 4.4W (API level 20) 測試 沒有閃退的狀況

**Comment by yiming330** [comment]
Dear Jason, 我們嘗試用模擬器去測試, 並沒有閃退的狀況, 也找了HTC M8 (Android 4.4.2) 的實機來測試, 仍然無法複製出閃退的狀況. 這個issue我們只能先放在pending, 再麻煩你們幫忙再問問看借到實機的可能, 或是可以請香港的同事幫忙確認這是偶發狀況或是持續性狀況, 是單一事件或是在每台Nexus 5都會發生. 也可以建議消費者先移除安裝, 再重新由Google Play下載一次app.

**Comment by yiming330** [comment]
附上Nexus 5模擬器連上Air Bank後開啟app的畫面.
![2014-07-07 1 13 24](https://cloud.githubusercontent.com/assets/5311668/3489492/33c75ff2-0531-11e4-9114-0c9762582d24.png)

**Comment by PQI-APP** [comment]
目前只有回報過一筆, 客服單位亦已處理完畢; 後續並無其他Android 4.4 device 有此狀況發生; 會持續追蹤
感謝

**Comment by yiming330** [comment]
Closing the issue for now. Will reopen it if reported by the customer support team.
