### ISSUE TITLE
Air Bank  以Windows 7連接會需要輸入Pin Code. 

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#2]
![air bank](https://cloud.githubusercontent.com/assets/8001211/3611234/0189d802-0d98-11e4-9b9e-9dfedcd697fa.jpg)

Pin Code 是什麼？

**Comment by yiming330** [comment]
Ernest, please try to reproduce the issue in Windows 7.

**Comment by wuboy0307** [comment]
這是使用WPS連上router時的正常現象
http://www.tp-link.tw/article/?faqid=494
USER其實只要在前一個畫面選擇 Connect to the network without setting it up 應該就可以了

**Comment by yiming330** [comment]
Closing the issue as it's been resolved and replied to end user.
