### ISSUE TITLE
Air Bank APP 上傳按鈕不見了

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#3]
PQI Air Bank+ 的上傳Button 不見了 導致APP 無法上傳或是下載檔案;請協助處理
Android 4.4.2 
Smartphone Model: LG G3

**Comment by yiming330** [comment]
Ernest, please test the scenario in your simulator when you receive the PQI Connect drive.

**Comment by wuboy0307** [comment]
使用與 LG G3 相同解析度的 emulator (1440 x 2560) 測試， 上傳Button是看得到的，可能要提供用戶的截圖比較能看出問題，以確認是在哪一個步驟看不到上傳按鈕，SD卡是否有正確插入。
![2014-07-19 3 04 40](https://cloud.githubusercontent.com/assets/2128976/3630756/c9d13e74-0eae-11e4-9cb6-e4371e82c422.png)

**Comment by PQI-APP** [comment]
G3 截圖畫面 第一張是在Air Bank 內的圖片 無法下載, 第二張是在手機上面的照片無法上傳至Air Bank. 
![screenshot_2014-07-21-10-04-23](https://cloud.githubusercontent.com/assets/8001211/3639459/d2acdb46-107c-11e4-8b2a-d3ab5e9218f1.png)
![screenshot_2014-07-21-10-03-37](https://cloud.githubusercontent.com/assets/8001211/3639461/daeeb478-107c-11e4-9f88-ea9468105014.png)

**Comment by wuboy0307** [comment]
正常來說，4.4的界面要有虛擬鍵盤的menu button (最右邊的那三點)
![normal](https://cloud.githubusercontent.com/assets/2128976/3639573/88918e3a-1081-11e4-8a96-db81bc06fc06.png)

然而我確認過LG G3的硬體規格， 這狀況應該是因為LG G3 仍然有把長按task switcher就變成menu button的功能做進去，導致4.4正常應該出現的軟體鍵盤沒有menu button.
請用戶試試看長按task switcher (右下方那個)，看看有沒有出現上傳按鈕

參考以下網站
http://www.hksilicon.com/kb/articles/512723/LG-G3menu
http://www.androidcentral.com/lg-g3-has-menu-button-heres-where-to-find-it

**Comment by yiming330** [comment]
The issue has been resolved, and explained to end user. It's not a bug, just user education needed.
