### ISSUE TITLE
外置卡的資料無法呈現

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#7]
1>    未能讀取Android手機外置卡 (microSD卡) 內之資料，以至無法上傳資料至PQI Air Bank，以使用Samsung手機客戶居多。
2>    Apple (IOS) 裝置上之影片或音樂檔案未能上傳至PQI Air Bank，手機目錄只有顯示相片檔案。
3>    App介面不夠人性化，要多重操作或配合手機不同按鍵才能作出指令。

**Comment by yiming330** [comment]
針對您提出的幾個問題, 我們做了測試跟調查, 調查結果如下:

1>    經過檢查app的功能及原始碼, Air系列app目前並沒有讀取external storage的功能, 並非手機或是作業系統造成的問題 我們認為, 這個並不算是bug, 
2>   這個問題合理的推測, 使用者是想要從iOS的iTunes library 將音樂或是影片傳出來. 這個在iOS裡面是不被允許的. 會有版權的問題. 請再幫忙確認使用者的問題是否如同上述行為.
3>    App介面的重新規劃, 可以另案討論. 或許可以多收集一些建議, 我們一併開會來討論, 然後做更完整的規劃.
